// lib/mock.ts
import { Post, User, Category, Comment, Role, PostStatus } from "@/lib/types";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Technology", slug: "technology", createdAt: "2024-01-01T00:00:00Z" },
  { id: "cat-2", name: "Travel",     slug: "travel",     createdAt: "2024-01-01T00:00:00Z" },
  { id: "cat-3", name: "Food",       slug: "food",       createdAt: "2024-01-01T00:00:00Z" },
];

export const mockUsers: User[] = [
  {
    id:        "user-1",
    name:      "Alice Admin",
    username:  "alice",
    email:     "alice@example.com",
    avatar:    "https://api.dicebear.com/7.x/avataaars/svg?seed=alice",
    bio:       "Platform administrator and tech enthusiast.",
    role:      Role.ADMIN,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id:        "user-2",
    name:      "Bob Author",
    username:  "bob",
    email:     "bob@example.com",
    avatar:    "https://api.dicebear.com/7.x/avataaars/svg?seed=bob",
    bio:       "Writer, traveller, and coffee addict.",
    role:      Role.AUTHOR,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
];

export const mockPosts: Post[] = [
  {
    id:            "post-1",
    title:         "Getting Started with Next.js 14",
    slug:          "getting-started-with-nextjs-14",
    excerpt:       "A comprehensive guide to building modern web apps with Next.js 14 and the App Router.",
    content:       "<h2>Introduction</h2><p>Next.js 14 introduces the stable App Router...</p>",
    featuredImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-1",
    author:        { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    categoryId:    "cat-1",
    category:      { id: "cat-1", name: "Technology", slug: "technology" },
    publishedAt:   "2024-03-01T10:00:00Z",
    createdAt:     "2024-03-01T08:00:00Z",
    updatedAt:     "2024-03-01T10:00:00Z",
  },
  {
    id:            "post-2",
    title:         "Top 10 Hidden Beaches in Southeast Asia",
    slug:          "top-10-hidden-beaches-southeast-asia",
    excerpt:       "Discover secluded paradise beaches away from the tourist crowds.",
    content:       "<h2>Why Southeast Asia?</h2><p>Southeast Asia holds some of the world's most stunning coastlines...</p>",
    featuredImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-2",
    author:        { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    categoryId:    "cat-2",
    category:      { id: "cat-2", name: "Travel", slug: "travel" },
    publishedAt:   "2024-03-05T12:00:00Z",
    createdAt:     "2024-03-05T09:00:00Z",
    updatedAt:     "2024-03-05T12:00:00Z",
  },
  {
    id:            "post-3",
    title:         "The Perfect Homemade Sourdough Bread",
    slug:          "perfect-homemade-sourdough-bread",
    excerpt:       "Master the art of sourdough with this step-by-step guide.",
    content:       "<h2>The Starter</h2><p>A good sourdough begins with a healthy, active starter...</p>",
    featuredImage: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-2",
    author:        { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    categoryId:    "cat-3",
    category:      { id: "cat-3", name: "Food", slug: "food" },
    publishedAt:   "2024-03-08T14:00:00Z",
    createdAt:     "2024-03-08T11:00:00Z",
    updatedAt:     "2024-03-08T14:00:00Z",
  },
  {
    id:            "post-4",
    title:         "TypeScript Best Practices in 2024",
    slug:          "typescript-best-practices-2024",
    excerpt:       "Level up your TypeScript with these patterns and techniques.",
    content:       "<h2>Use Strict Mode</h2><p>Always enable strict mode in your tsconfig...</p>",
    featuredImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-1",
    author:        { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    categoryId:    "cat-1",
    category:      { id: "cat-1", name: "Technology", slug: "technology" },
    publishedAt:   "2024-03-10T09:00:00Z",
    createdAt:     "2024-03-10T07:00:00Z",
    updatedAt:     "2024-03-10T09:00:00Z",
  },
  {
    id:            "post-5",
    title:         "Street Food Guide: Bangkok",
    slug:          "street-food-guide-bangkok",
    excerpt:       "Navigate Bangkok's incredible street food scene like a local.",
    content:       "<h2>Where to Start</h2><p>Bangkok's Yaowarat Road (Chinatown) is the ultimate street food destination...</p>",
    featuredImage: "https://images.unsplash.com/photo-1503764654157-72d979d9af2f?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-2",
    author:        { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    categoryId:    "cat-3",
    category:      { id: "cat-3", name: "Food", slug: "food" },
    publishedAt:   "2024-03-12T11:00:00Z",
    createdAt:     "2024-03-12T08:00:00Z",
    updatedAt:     "2024-03-12T11:00:00Z",
  },
  {
    id:            "post-6",
    title:         "Building a REST API with Prisma and Next.js",
    slug:          "building-rest-api-prisma-nextjs",
    excerpt:       "A practical guide to creating type-safe APIs using Prisma ORM and Next.js route handlers.",
    content:       "<h2>Setup</h2><p>Start by installing Prisma and initializing your schema...</p>",
    featuredImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-1",
    author:        { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    categoryId:    "cat-1",
    category:      { id: "cat-1", name: "Technology", slug: "technology" },
    publishedAt:   "2024-03-15T10:00:00Z",
    createdAt:     "2024-03-15T08:00:00Z",
    updatedAt:     "2024-03-15T10:00:00Z",
  },
  {
    id:            "post-7",
    title:         "Draft: Exploring the Italian Riviera",
    slug:          "exploring-italian-riviera",
    excerpt:       "A draft post about the stunning Italian Riviera coastline.",
    content:       "<h2>Cinque Terre</h2><p>Work in progress...</p>",
    featuredImage: null,
    status:        PostStatus.DRAFT,
    authorId:      "user-2",
    author:        { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    categoryId:    "cat-2",
    category:      { id: "cat-2", name: "Travel", slug: "travel" },
    publishedAt:   null,
    createdAt:     "2024-03-16T09:00:00Z",
    updatedAt:     "2024-03-16T09:00:00Z",
  },
  {
    id:            "post-8",
    title:         "Draft: React Server Components Deep Dive",
    slug:          "react-server-components-deep-dive",
    excerpt:       "Understanding RSC patterns and when to use them.",
    content:       "<p>Draft content...</p>",
    featuredImage: null,
    status:        PostStatus.DRAFT,
    authorId:      "user-1",
    author:        { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    categoryId:    "cat-1",
    category:      { id: "cat-1", name: "Technology", slug: "technology" },
    publishedAt:   null,
    createdAt:     "2024-03-17T10:00:00Z",
    updatedAt:     "2024-03-17T10:00:00Z",
  },
  {
    id:            "post-9",
    title:         "Vegan Recipes for Beginners",
    slug:          "vegan-recipes-for-beginners",
    excerpt:       "Easy, delicious vegan meals you can cook in under 30 minutes.",
    content:       "<h2>Why Go Vegan?</h2><p>Plant-based eating has never been easier or more delicious...</p>",
    featuredImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-2",
    author:        { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    categoryId:    "cat-3",
    category:      { id: "cat-3", name: "Food", slug: "food" },
    publishedAt:   "2024-03-18T13:00:00Z",
    createdAt:     "2024-03-18T10:00:00Z",
    updatedAt:     "2024-03-18T13:00:00Z",
  },
  {
    id:            "post-10",
    title:         "Japan Rail Pass: Complete Guide",
    slug:          "japan-rail-pass-complete-guide",
    excerpt:       "Everything you need to know to travel Japan by rail efficiently.",
    content:       "<h2>Is It Worth It?</h2><p>The JR Pass pays for itself if you plan multiple city hops...</p>",
    featuredImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    status:        PostStatus.PUBLISHED,
    authorId:      "user-1",
    author:        { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    categoryId:    "cat-2",
    category:      { id: "cat-2", name: "Travel", slug: "travel" },
    publishedAt:   "2024-03-20T09:00:00Z",
    createdAt:     "2024-03-20T07:00:00Z",
    updatedAt:     "2024-03-20T09:00:00Z",
  },
];

export const mockComments: Comment[] = [
  {
    id:        "comment-1",
    body:      "Great article! Really helped me get started with Next.js.",
    postId:    "post-1",
    authorId:  "user-2",
    author:    { id: "user-2", name: "Bob Author", username: "bob", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob" },
    createdAt: "2024-03-02T10:00:00Z",
    updatedAt: "2024-03-02T10:00:00Z",
  },
  {
    id:        "comment-2",
    body:      "Amazing beach recommendations. Added them all to my bucket list!",
    postId:    "post-2",
    authorId:  "user-1",
    author:    { id: "user-1", name: "Alice Admin", username: "alice", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice" },
    createdAt: "2024-03-06T08:00:00Z",
    updatedAt: "2024-03-06T08:00:00Z",
  },
];

// Convenience helpers used by D2/D3 without writing filter logic themselves
export const mockPublishedPosts = mockPosts.filter(p => p.status === PostStatus.PUBLISHED);
export const mockDraftPosts     = mockPosts.filter(p => p.status === PostStatus.DRAFT);

export function getMockPostBySlug(slug: string): Post | undefined {
  return mockPosts.find(p => p.slug === slug);
}

export function getMockPostsByAuthor(username: string): Post[] {
  return mockPublishedPosts.filter(p => p.author?.username === username);
}

export function getMockPostsByCategory(categorySlug: string): Post[] {
  return mockPublishedPosts.filter(p => p.category?.slug === categorySlug);
}